name: "Terraform CI/CD Pipeline"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    name: "Terraform Automation"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./environments/dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Usar v3.1.2 para corregir las claves PGP expiradas de HashiCorp
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.9.0
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -upgrade
      
# Crear el archivo directamente en la carpeta actual (environments/dev)
      - name: Create Dummy SSH Public Key
        run: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdummykeygithubactions" > nginx-server.key.pub
      
      - name: Terraform Plan
        env:
          TF_VAR_aws_region: "us-east-1"
          TF_VAR_environment: "dev"
          TF_VAR_instance_type: "t3.micro"
          TF_VAR_public_key_path: "nginx-server.key.pub"
          TF_VAR_root_volume_size: "8"
          TF_VAR_db_name: "appdb"
          TF_VAR_db_user: "dbadmin"
          TF_VAR_db_password: "password"
        run: terraform plan